compiler:
  - gcc

language: c

cache:
  directories:
    -$HOME/petsc

before_install:
  - sudo apt-get install gfortran

install:
  - |
    git clone -b maint https://bitbucket.org/petsc/petsc petsc
    cd petsc/
    export PETSC_DIR=`pwd`
    export PETSC_ARCH=linux-gnu-c-complex
    ./configure PETSC_ARCH=${PETSC_ARCH} PETSC_DIR=${PETSC_DIR} --with-cc=gcc --with-cxx=g++ --with-fc=gfortran --download-fblaslapack --download-mpich --with-scalar-type=complex
    make PETSC_DIR=${PETSC_DIR} PETSC_ARCH=${PETSC_ARCH} all
    cd ..

script: make dm_utilities_tests

