compiler:
  - gcc

language: c

cache:
  directories:
    - petsc

addons:
  apt:
    packages:
      - gfortran

install:
  - |
    cd petsc/
    export PETSC_DIR=`pwd`
    export PETSC_ARCH=linux-gnu-c-complex
    cd ..

script:
  - make
  - make --version
  - ls obj
  - ls tests
  - make -n test
  - make test

