compiler:
  - gcc

language: c

cache:
  directories:
    - petsc

before_install:
  - sudo apt-get install gfortran

install:
  - |
    cd petsc/
    export PETSC_DIR=`pwd`
    export PETSC_ARCH=linux-gnu-c-complex
    cd ..

script: make

