compiler:
  - gcc

language: c

cache:
  directories:
    - petsc

addons:
  apt:
    packages:
      - gfortran

install:
  - |
    cd petsc/
    ls linux-gnu-c-complex/lib
    export PETSC_DIR=`pwd`
    export PETSC_ARCH=linux-gnu-c-complex
    cd ..

script: tests/travis_test.sh

